//! Writing the asset table into `OUT_DIR`.

use std::{fmt::Write as _, fs, path::Path};

use crate::{Asset, Error, Result};

/// The file [`Assets::emit`](crate::Assets::emit) writes, for `include!`.
pub const GENERATED_FILE: &str = "exos_assets.rs";

/// The generated source and the blobs it refers to.
pub(crate) struct Generated<'assets> {
    assets: &'assets [Asset],
}

impl core::fmt::Debug for Generated<'_> {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        formatter
            .debug_struct("Generated")
            .field("assets", &self.assets.len())
            .finish()
    }
}

impl<'assets> Generated<'assets> {
    pub(crate) fn new(assets: &'assets [Asset]) -> Self {
        Self { assets }
    }

    /// Writes one blob per asset plus the table that references them.
    ///
    /// The bytes go to sibling files and come back through `include_bytes!`.
    /// Emitting them as array literals would make rustc parse a few hundred
    /// thousand tokens per asset.
    ///
    /// The table names `Asset` unqualified, so the including module decides
    /// where that comes from.
    pub(crate) fn write(&self, out: &Path) -> Result<()> {
        let mut code = String::from("// Generated by exos-build. Do not edit.\n");
        code.push_str("pub(crate) static ASSETS: &[Asset] = &[\n");

        for asset in self.assets {
            let blob = format!("{}.blob", asset.file);
            let path = out.join(&blob);

            fs::write(&path, &asset.bytes).map_err(|source| Error::Io {
                path: path.clone(),
                source,
            })?;

            // Writing into a String is infallible.
            let _ = writeln!(
                code,
                "    Asset::new({:?}, {:?}, {:?}, \
                 include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{}\"))),",
                asset.name, asset.file, asset.content_type, blob
            );
        }

        code.push_str("];\n");

        let path = out.join(GENERATED_FILE);
        fs::write(&path, code).map_err(|source| Error::Io { path, source })
    }
}
