[package]
description = "TodoMVC, written in exos"
name = "todos"
publish = false
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
axum.workspace = true
exos.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
exos-test.workspace = true

[lints]
workspace = true
