[package]
description = "Macros for exos: view!, route attributes, models and live fragments"
documentation = "https://docs.rs/exos-macro"
name = "exos-macro"
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
exos-build.workspace = true
proc-macro2.workspace = true
quote.workspace = true
rstml.workspace = true
syn.workspace = true

[lints]
workspace = true
