//! Typed signal handles.
//!
//! A signal is a named piece of state in the browser. It is defined once, in
//! Rust, and the handle is what templates use, so renaming it is a compile
//! error at every use site.
//!
//! ```ignore
//! let gone = signal!(gone = false);   // Signal<bool>
//!
//! view! {
//!     <li id={ row_id } {&gone} {show(!gone.get())}>
//!         <button {on_click(|_| gone.set(true))}>"Delete"</button>
//!     </li>
//! }
//! ```
//!
//! Signals hold state the server does **not** own: a row pending deletion, a
//! modal, a draft input, a selection. Server-owned state lives in markup and
//! changes only by a patch. Mirroring it into a signal gives one value two
//! sources of truth, and they drift as soon as a patch lands.

use core::marker::PhantomData;

use serde::Serialize;
use serde_json::Value;

use crate::{IntoJs, Js, emit};

/// A named piece of client state.
///
/// The name resolves against the DOM scope the signal is declared on, so two
/// rows can both call theirs `gone` without colliding.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Signal<T> {
    name: String,
    initial: Value,
    marker: PhantomData<fn() -> T>,
}

impl<T> Signal<T> {
    /// A signal with a starting value.
    ///
    /// Prefer [`signal!`](crate::signal), which takes the name from the
    /// binding so the two cannot disagree. `initial` is taken by value so that
    /// it also fixes `T`, sparing every call site a turbofish.
    #[must_use]
    pub fn new(name: impl Into<String>, initial: T) -> Self
    where
        T: Serialize,
    {
        let initial = serde_json::to_value(&initial).unwrap_or(Value::Null);
        Self::with_value(name, initial)
    }

    /// A signal whose starting value is already serialized.
    ///
    /// `#[model]` uses this: it has the model's `Default` as one JSON object
    /// and splits it per field, so it never needs `T: Serialize` for each
    /// field on its own.
    #[must_use]
    pub fn with_value(name: impl Into<String>, initial: Value) -> Self {
        Self {
            name: name.into(),
            initial,
            marker: PhantomData,
        }
    }

    /// The name this signal is declared under.
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    /// The value it starts at.
    #[must_use]
    pub fn initial(&self) -> &Value {
        &self.initial
    }

    /// Reads the signal in the browser.
    #[must_use]
    pub fn get(&self) -> Js<T> {
        Js::raw(format!("$.{}", self.name))
    }

    /// Writes it.
    ///
    /// # Panics
    ///
    /// If called outside a handler; see [`emit`].
    pub fn set(&self, value: impl IntoJs<T>) {
        emit(format!("$.{} = {}", self.name, value.into_js().source()));
    }
}

impl Signal<bool> {
    /// Flips the signal.
    ///
    /// # Panics
    ///
    /// If called outside a handler; see [`emit`].
    pub fn toggle(&self) {
        emit(format!("$.{name} = !$.{name}", name = self.name));
    }
}

impl<T> Signal<Vec<T>> {
    /// Empties the collection.
    ///
    /// # Panics
    ///
    /// If called outside a handler; see [`emit`].
    pub fn clear(&self) {
        emit(format!("$.{} = []", self.name));
    }

    /// Appends a value.
    ///
    /// A fresh array is assigned rather than mutating in place, because that
    /// is what makes the runtime notice the change.
    ///
    /// # Panics
    ///
    /// If called outside a handler; see [`emit`].
    pub fn push(&self, value: impl IntoJs<T>) {
        emit(format!(
            "$.{name} = [...$.{name}, {}]",
            value.into_js().source(),
            name = self.name
        ));
    }

    /// Adds the value when absent and removes it when present, which is what
    /// a checkbox does.
    ///
    /// # Panics
    ///
    /// If called outside a handler; see [`emit`].
    pub fn toggle_member(&self, value: impl IntoJs<T>) {
        let value = value.into_js().into_source();

        emit(format!(
            "$.{name} = $.{name}.includes({value}) \
             ? $.{name}.filter(held => held !== {value}) \
             : [...$.{name}, {value}]",
            name = self.name
        ));
    }
}

/// A typed reference to one field of a model.
///
/// Generated by `#[model]` as an associated constant, so error reporting and
/// form handling key off something the compiler checks rather than a string
/// that quietly stops matching when the field is renamed.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct Field<M> {
    name: &'static str,
    marker: PhantomData<fn() -> M>,
}

impl<M> Field<M> {
    /// Names a field of `M`.
    #[must_use]
    pub const fn new(name: &'static str) -> Self {
        Self {
            name,
            marker: PhantomData,
        }
    }

    /// The field's name.
    #[must_use]
    pub const fn name(&self) -> &'static str {
        self.name
    }
}

/// Declares a signal, taking its client-side name from the Rust binding.
///
/// ```
/// # use exos::signal;
/// let gone = signal!(gone = false);
/// assert_eq!(gone.name(), "gone");
/// ```
#[macro_export]
macro_rules! signal {
    ($name:ident = $initial:expr) => {
        $crate::Signal::new(::core::stringify!($name), $initial)
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::record;

    #[test]
    fn a_handle_reads_and_writes_by_name() {
        let gone = Signal::new("gone", false);

        assert_eq!(gone.get().source(), "$.gone");
        assert_eq!(record(|| gone.set(true)), "$.gone = true");
        assert_eq!(record(|| gone.toggle()), "$.gone = !$.gone");
    }

    #[test]
    fn collection_helpers_assign_rather_than_mutate() {
        let picked: Signal<Vec<u32>> = Signal::new("picked", Vec::new());

        assert_eq!(record(|| picked.clear()), "$.picked = []");
        assert!(record(|| picked.push(3_u32)).starts_with("$.picked = [...$.picked,"));
    }

    #[test]
    fn toggling_a_member_is_symmetric() {
        let picked: Signal<Vec<u32>> = Signal::new("picked", Vec::new());
        let script = record(|| picked.toggle_member(7_u32));

        assert!(script.contains("includes(7)"));
        assert!(script.contains("filter(held => held !== 7)"));
    }

    #[test]
    fn the_macro_takes_the_name_from_the_binding() {
        let gone = signal!(gone = false);

        assert_eq!(gone.name(), "gone");
        assert_eq!(gone.initial(), &serde_json::json!(false));
    }

    #[test]
    fn a_field_token_carries_its_name() {
        struct Draft;
        const SKU: Field<Draft> = Field::new("sku");

        assert_eq!(SKU.name(), "sku");
    }
}
