//! Expansion of `locales!`.

use exos_cldr::{Direction, Entry};
use proc_macro2::{Ident, Span, TokenStream};
use quote::{format_ident, quote};
use syn::{
    Attribute, LitStr, Token,
    parse::{Parse, ParseStream},
    punctuated::Punctuated,
};

mod rule;

/// Expands the declaration into `Locale` and one module per language.
pub(crate) fn expand(input: TokenStream) -> TokenStream {
    match syn::parse2::<Declaration>(input).and_then(|declaration| declaration.emit()) {
        Ok(tokens) => tokens,
        Err(error) => error.to_compile_error(),
    }
}

/// The whole invocation.
struct Declaration {
    locales: Vec<Declared>,
}

/// One `#[fallback] En = "en"` line.
struct Declared {
    /// Whatever documentation the line carried, kept so that a locale can be
    /// annotated like any other variant.
    docs: Vec<Attribute>,
    fallback: bool,
    variant: Ident,
    tag: LitStr,
}

impl Parse for Declaration {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        let locales = Punctuated::<Declared, Token![,]>::parse_terminated(input)?;

        Ok(Self {
            locales: locales.into_iter().collect(),
        })
    }
}

impl Parse for Declared {
    fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
        let attributes = input.call(Attribute::parse_outer)?;
        let variant = input.parse::<Ident>()?;
        input.parse::<Token![=]>()?;
        let tag = input.parse::<LitStr>()?;

        let mut docs = Vec::new();
        let mut fallback = false;

        for attribute in attributes {
            if attribute.path().is_ident("fallback") {
                fallback = true;
            } else if attribute.path().is_ident("doc") {
                docs.push(attribute);
            } else {
                return Err(syn::Error::new_spanned(
                    attribute,
                    "a locale takes documentation and `#[fallback]`, and nothing else",
                ));
            }
        }

        Ok(Self {
            docs,
            fallback,
            variant,
            tag,
        })
    }
}

impl Declaration {
    /// Everything the declaration generates: the enum, its constants and one
    /// module per language.
    fn emit(&self) -> syn::Result<TokenStream> {
        self.check()?;

        let fallback = &self
            .locales
            .iter()
            .find(|locale| locale.fallback)
            .ok_or_else(|| {
                syn::Error::new(
                    Span::call_site(),
                    "one locale has to carry `#[fallback]`, since resolving a locale always \
                     answers with one rather than with an option",
                )
            })?
            .variant;

        let variants: Vec<&Ident> = self.locales.iter().map(|locale| &locale.variant).collect();
        let tags: Vec<&LitStr> = self.locales.iter().map(|locale| &locale.tag).collect();
        let modules: Vec<Ident> = self.locales.iter().map(Declared::module).collect();

        let documented = self.locales.iter().map(|locale| {
            let variant = &locale.variant;
            let docs = &locale.docs;
            let summary = format!("The `{}` locale.", locale.tag.value());

            quote! {
                #[doc = #summary]
                #(#docs)*
                #variant
            }
        });

        // `check` has already refused a tag the table has no entry for, which
        // is what lets everything below read one out.
        let directions = self.locales.iter().map(|locale| {
            let direction = format_ident!("{}", rule::direction(locale.direction()));
            quote! { ::exos::Direction::#direction }
        });

        let symbols = self.locales.iter().map(Declared::symbols);
        let languages = self.locales.iter().map(Declared::language);

        let version = exos_cldr::VERSION;

        Ok(quote! {
            /// The languages this application is built in.
            ///
            /// Generated by `exos::locales!`, which is also where the tags,
            /// the fallback and the plural rules come from. Everything
            /// localization decides resolves this type, so it lives at the
            /// crate root and is named `crate::Locale` from wherever a message
            /// is written.
            #[derive(
                ::core::clone::Clone,
                ::core::marker::Copy,
                ::core::fmt::Debug,
                ::core::cmp::Eq,
                ::core::hash::Hash,
                ::core::cmp::Ord,
                ::core::cmp::PartialEq,
                ::core::cmp::PartialOrd,
            )]
            pub enum Locale {
                #(#documented,)*
            }

            impl Locale {
                /// Every declared locale, in the order they were declared.
                pub const ALL: &'static [Self] = &[#(Self::#variants),*];

                /// The locale a request resolves to when nothing better is
                /// known about who is reading.
                pub const FALLBACK: Self = Self::#fallback;

                /// The CLDR release the plural rules below were generated
                /// from.
                pub const CLDR_VERSION: &'static str = #version;

                /// The tag this locale was declared with.
                ///
                /// It is what `lang` on the document carries, and what the
                /// browser hands to `Intl`, so the two halves of a page agree
                /// on the language by agreeing on this string.
                pub const fn tag(self) -> &'static str {
                    match self {
                        #(Self::#variants => #tags,)*
                    }
                }

                /// Which way this locale's script runs.
                ///
                /// From the script the tag names, or from the one CLDR expects
                /// the language to be written in where it names none.
                pub const fn direction(self) -> ::exos::Direction {
                    match self {
                        #(Self::#variants => #directions,)*
                    }
                }

                /// The locale declared with `tag`, if there is one.
                ///
                /// The tag is compared whole and without regard to case, so
                /// this answers for what an application declared and not for
                /// what a browser asked for. Matching an `Accept-Language`
                /// header is a wider question, and it belongs to resolution.
                pub fn from_tag(tag: &str) -> ::core::option::Option<Self> {
                    Self::ALL
                        .iter()
                        .copied()
                        .find(|locale| tag.eq_ignore_ascii_case(locale.tag()))
                }

                /// The symbols this language writes a whole number with.
                ///
                /// CLDR's answer for the language, which is what the browser's
                /// `Intl.NumberFormat` answers with too, so that a page and
                /// its runtime write a number the same way.
                pub const fn symbols(self) -> ::exos::Symbols {
                    match self {
                        #(Self::#variants => #symbols,)*
                    }
                }

                /// `count` written the way this language writes a whole
                /// number.
                ///
                /// What a message does with a count it puts into a sentence.
                /// An application formatting one itself, or formatting
                /// anything else numeric, is the same call.
                pub fn number(self, count: impl ::exos::Count) -> ::std::string::String {
                    ::exos::Symbols::number(&self.symbols(), count)
                }

                /// The plural category `count` falls in, spelled the way every
                /// language spells it.
                ///
                /// The typed answer is in the locale's own module, where the
                /// categories are exactly the ones the language has. This one
                /// crosses locales, which is what a projection into the
                /// browser and a test need, and what a message never does.
                pub fn category(self, count: u64) -> ::exos::PluralCategory {
                    match self {
                        #(Self::#variants => #modules::category(count).into(),)*
                    }
                }
            }

            // What exos itself reads, since it cannot name this type. Every
            // item delegates to the inherent one above, which is where the
            // documentation is and which an application reaches with nothing
            // imported.
            impl ::exos::LocaleSet for Locale {
                const ALL: &'static [Self] = Self::ALL;
                const FALLBACK: Self = Self::FALLBACK;

                fn tag(self) -> &'static str {
                    Locale::tag(self)
                }

                fn direction(self) -> ::exos::Direction {
                    Locale::direction(self)
                }
            }

            impl ::exos::Sealed for Locale {}

            // How `messages!` reaches a language's categories. An arm names a
            // variant, the module beside this one is named after a tag, and
            // nothing in an invocation of that macro can see which tag a
            // variant was declared with.
            #[doc(hidden)]
            pub mod __locales {
                #(pub use super::#modules as #variants;)*
            }

            #(#languages)*
        })
    }

    /// Refuses a declaration nothing good can come of.
    fn check(&self) -> syn::Result<()> {
        if self.locales.is_empty() {
            return Err(syn::Error::new(
                Span::call_site(),
                "an application declares at least one locale",
            ));
        }

        let mut fallbacks = self.locales.iter().filter(|locale| locale.fallback).skip(1);

        if let Some(second) = fallbacks.next() {
            return Err(syn::Error::new_spanned(
                &second.variant,
                "only one locale is the fallback",
            ));
        }

        for (index, locale) in self.locales.iter().enumerate() {
            let tag = locale.tag.value();

            if locale.entry().is_none() {
                return Err(syn::Error::new_spanned(
                    &locale.tag,
                    format!(
                        "CLDR has no plural rules for `{tag}`. A tag is matched by dropping \
                         subtags, so `de-AT` resolves through `de`, but the language itself \
                         has to be one CLDR knows",
                    ),
                ));
            }

            let earlier = self.locales[..index]
                .iter()
                .any(|other| other.tag.value().eq_ignore_ascii_case(&tag));

            if earlier {
                return Err(syn::Error::new_spanned(
                    &locale.tag,
                    format!("`{tag}` is declared twice"),
                ));
            }

            if self.locales[..index]
                .iter()
                .any(|other| other.module() == locale.module())
            {
                return Err(syn::Error::new_spanned(
                    &locale.tag,
                    format!(
                        "`{tag}` would generate the module `{}`, which another locale already \
                         generates",
                        locale.module()
                    ),
                ));
            }
        }

        Ok(())
    }
}

impl Declared {
    /// The entry in the vendored table this locale resolves to.
    fn entry(&self) -> Option<&'static Entry> {
        Entry::lookup(&self.tag.value())
    }

    /// The same entry, once the declaration has been checked.
    fn checked(&self) -> &'static Entry {
        self.entry()
            .expect("a tag with no entry has already been refused")
    }

    /// Which way this locale runs.
    fn direction(&self) -> Direction {
        self.checked().direction_of(&self.tag.value())
    }

    /// What this locale writes a whole number with.
    ///
    /// The table is keyed by language, so a locale declared with a region gets
    /// the language's symbols. That is wrong for the handful of regions which
    /// write numbers differently from the language they belong to, and it is
    /// what the table has.
    fn symbols(&self) -> TokenStream {
        let symbols = self.checked().symbols;

        let digits = symbols.digits;
        let group = symbols.group;
        let minus = symbols.minus;
        let grouping = symbols.grouping;
        let secondary = symbols.secondary_grouping;
        let minimum = symbols.minimum_grouping_digits;

        quote! {
            ::exos::Symbols {
                digits: #digits,
                group: #group,
                minus: #minus,
                grouping: #grouping,
                secondary_grouping: #secondary,
                minimum_grouping_digits: #minimum,
            }
        }
    }

    /// What the locale's module is called: its tag, as an identifier.
    ///
    /// A tag that spells a keyword becomes a raw identifier rather than an
    /// error, since Assamese is `as` and that is not something an application
    /// gets to choose.
    fn module(&self) -> Ident {
        let name = self.tag.value().to_lowercase().replace('-', "_");
        let span = self.tag.span();

        match syn::parse_str::<Ident>(&name) {
            Ok(_) => Ident::new(&name, span),
            Err(_) => Ident::new_raw(&name, span),
        }
    }

    /// The module holding this language's categories and the rule picking one.
    fn language(&self) -> TokenStream {
        let tag = self.tag.value();
        let module = self.module();
        let rules = self.checked().rules;

        let variants: Vec<Ident> = rules
            .iter()
            .map(|rule| format_ident!("{}", rule::category(rule.category)))
            .collect();

        let documented = rules.iter().zip(&variants).map(|(rule, variant)| {
            let keyword = rule.category.keyword();

            let summary = if rule.samples.is_empty() {
                format!("CLDR's `{keyword}`, which no whole number falls in.")
            } else {
                format!("CLDR's `{keyword}`: {}.", rule.samples)
            };

            quote! {
                #[doc = #summary]
                #variant
            }
        });

        // Built from the bottom up, since the last category is the one that
        // always applies and every earlier one wraps what is left of the list.
        let mut body = {
            let last = variants
                .last()
                .expect("a language has at least one category");
            quote! { Plural::#last }
        };

        for (index, (rule, variant)) in rules.iter().zip(&variants).rev().skip(1).enumerate() {
            let condition =
                rule::condition(rule).expect("only the last category applies unconditionally");

            // The innermost arm is the category that always applies and needs
            // its braces; everything above it wraps an `if`, and `else if` is
            // how a person would have written the chain.
            body = if index == 0 {
                quote! { if #condition { Plural::#variant } else { #body } }
            } else {
                quote! { if #condition { Plural::#variant } else #body }
            };
        }

        // A language with one category asks nothing about the count, and an
        // unused binding is a warning in the crate this lands in.
        let count = if rules.len() == 1 {
            format_ident!("_count")
        } else {
            format_ident!("count")
        };

        let module_docs =
            format!("The plural categories `{tag}` has, and the rule that picks one.");
        let enum_docs = format!("Which plural category a count falls in, for `{tag}`.");
        let function_docs = format!("The category `{tag}` puts `count` in.");

        quote! {
            #[doc = #module_docs]
            pub mod #module {
                #[doc = #enum_docs]
                ///
                /// Exactly the categories CLDR gives the language and no
                /// others, which is what makes a message that forgets one a
                /// non-exhaustive match rather than a string nobody sees.
                #[derive(
                    ::core::clone::Clone,
                    ::core::marker::Copy,
                    ::core::fmt::Debug,
                    ::core::cmp::Eq,
                    ::core::hash::Hash,
                    ::core::cmp::Ord,
                    ::core::cmp::PartialEq,
                    ::core::cmp::PartialOrd,
                )]
                pub enum Plural {
                    #(#documented,)*
                }

                impl ::core::convert::From<Plural> for ::exos::PluralCategory {
                    fn from(plural: Plural) -> Self {
                        match plural {
                            #(Plural::#variants => Self::#variants,)*
                        }
                    }
                }

                // A category is a domain a message branches on like any other,
                // and this is the list a projection walks.
                impl ::exos::Enumerable for Plural {
                    const ALL: &'static [Self] = &[#(Plural::#variants),*];
                }

                #[doc = #function_docs]
                ///
                /// Counted in whole numbers, so the operands CLDR has for the
                /// digits after a decimal point are zero and the rule collapses
                /// to what is written here.
                pub const fn category(#count: u64) -> Plural {
                    #body
                }
            }
        }
    }
}

#[cfg(test)]
#[expect(
    clippy::expect_used,
    reason = "a failing assertion is the point of a test"
)]
mod tests {
    use super::*;

    fn expand_ok(input: &str) -> String {
        expand(input.parse().expect("valid input")).to_string()
    }

    #[test]
    fn declares_an_enum_with_a_variant_per_locale() {
        let expanded = expand_ok(r#"De = "de", #[fallback] En = "en","#);

        assert!(expanded.contains("pub enum Locale"));
        assert!(expanded.contains("FALLBACK : Self = Self :: En"));
        assert!(expanded.contains(r#"Self :: De => "de""#));
    }

    /// exos cannot name the enum this generates, so it reads it through a
    /// trait, and a set that carried no implementation of it would compile and
    /// then be unresolvable.
    #[test]
    fn the_set_answers_the_framework_as_well_as_the_application() {
        let expanded = expand_ok(r#"#[fallback] En = "en","#);

        assert!(expanded.contains("impl :: exos :: LocaleSet for Locale"));
        assert!(expanded.contains("impl :: exos :: Sealed for Locale"));
    }

    /// The categories are the language's own, so German gets two and Arabic
    /// gets six, and a message written against either is checked against that.
    #[test]
    fn a_language_gets_exactly_its_own_categories() {
        let german = expand_ok(r#"#[fallback] De = "de","#);
        let arabic = expand_ok(r#"#[fallback] Ar = "ar","#);

        assert!(german.contains("One"));
        assert!(!german.contains("Few"), "german has no `few`");
        assert!(!german.contains("Zero"), "german has no `zero`");

        for category in ["Zero", "One", "Two", "Few", "Many", "Other"] {
            assert!(arabic.contains(category), "arabic is missing {category}");
        }
    }

    /// The whole reason the table is collapsed at generation time: German asks
    /// one question, and asks it of the count rather than of six operands.
    #[test]
    fn an_integer_count_collapses_the_rule_to_one_comparison() {
        let expanded = expand_ok(r#"#[fallback] De = "de","#);

        assert!(
            expanded.contains("if count == 1 { Plural :: One } else { Plural :: Other }"),
            "{expanded}"
        );
    }

    /// A language with one category never looks at the count, and a binding
    /// nothing reads is a warning in whichever crate the macro expanded in.
    #[test]
    fn a_language_with_one_category_does_not_bind_the_count() {
        let expanded = expand_ok(r#"#[fallback] Ja = "ja","#);

        assert!(expanded.contains("pub const fn category (_count : u64)"));
    }

    #[test]
    fn a_region_resolves_through_its_language() {
        let expanded = expand_ok(r#"#[fallback] DeAt = "de-AT","#);

        assert!(expanded.contains("pub mod de_at"));
        assert!(expanded.contains("if count == 1"));
    }

    /// Assamese is `as`, which is a keyword, and an application does not get
    /// to pick a different tag for it.
    #[test]
    fn a_tag_that_spells_a_keyword_becomes_a_raw_identifier() {
        let expanded = expand_ok(r#"#[fallback] As = "as","#);

        assert!(expanded.contains("pub mod r#as"));
    }

    #[test]
    fn the_direction_follows_the_script_the_tag_names() {
        let latin = expand_ok(r#"#[fallback] Pa = "pa","#);
        let arabic = expand_ok(r#"#[fallback] PaArab = "pa-Arab","#);

        assert!(latin.contains("Direction :: LeftToRight"));
        assert!(arabic.contains("Direction :: RightToLeft"));
    }

    #[test]
    fn a_language_cldr_has_no_rules_for_is_refused() {
        let expanded = expand_ok(r#"#[fallback] Xx = "xx","#);

        assert!(expanded.contains("compile_error"));
        assert!(expanded.contains("no plural rules"));
    }

    /// Resolution answers with a locale rather than with an option, and that
    /// promise is only keepable if one of them is marked.
    #[test]
    fn a_declaration_without_a_fallback_is_refused() {
        assert!(expand_ok(r#"De = "de","#).contains("compile_error"));
    }

    #[test]
    fn two_fallbacks_are_refused() {
        let expanded = expand_ok(r#"#[fallback] De = "de", #[fallback] En = "en","#);

        assert!(expanded.contains("compile_error"));
        assert!(expanded.contains("only one locale is the fallback"));
    }

    #[test]
    fn a_tag_declared_twice_is_refused() {
        let expanded = expand_ok(r#"#[fallback] De = "de", German = "DE","#);

        assert!(expanded.contains("compile_error"));
        assert!(expanded.contains("declared twice"));
    }

    #[test]
    fn an_empty_declaration_is_refused() {
        assert!(expand_ok("").contains("compile_error"));
    }

    #[test]
    fn an_attribute_that_is_not_understood_is_refused() {
        let expanded = expand_ok(r#"#[default] #[fallback] En = "en","#);

        assert!(expanded.contains("compile_error"));
    }
}
