[package]
description = "Build-time asset pipeline for exos"
documentation = "https://docs.rs/exos-build"
name = "exos-build"
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
lightningcss.workspace = true
minifier.workspace = true
sha2.workspace = true
thiserror.workspace = true

[lints]
workspace = true
